backspace_mult: 0.03
arrow_mult: 0.02
num_layers: 5
keys_per_row:
  NUM: 7
  TOP: 7
  HOM: 7
  BOT: 6
  MOD: 5
  TMB: 3
# Right hand only, assume left hand is the same + 0.05
# Use None for reserved keys
key_penalties:
  NUM: [20, 20, 15, 15, 15, 15, 15]
  TOP: [20, 5, 3, 1.5, 2, 7.5, 15]
  HOM: [10, 2, 0, 0,.5, 2, 4]
  BOT: [3.5, 0, 2.0, 2.5, 4, 6]
  MOD: [4, 4.5, 5, 5.5, 10]
  TMB: [3, 0, 2]
fingers:
  NUM: [I, I, M, M, R, R, R]
  TOP: [I, I, I, M, R, R, R]
  HOM: [I, I, I, M, R, P, P]
  BOT: [I, I, M, R, P, P]
  MOD: [I, M, R, P, P]
  TMB: [T, T, T]
penalties: # Some penalties are WPM drops from https://mathematicalmulticore.wordpress.com/2011/11/27/typing-data-preliminary-analysis/
  location: 1
  layers: [0, 3, 3, 3, 10, 10]
  same_finger: 9
  same_hand: 14
  alternating_hand: 11
  long_jump_finger: 15
  long_jump_consecutive: 5
  long_jump_sandwich: 3
  long_jump_hand: 2
  roll_reversal: 10
  roll_out: 1
  roll_in: -10.0
  twist: 5
  finger_disbalance: 4

