esc_mult: 0.04
backspace_mult: 0.03
arrow_mult: 0.02
keys_per_row:
  NUM: 0
  TOP: 5
  HOM: 5
  BOT: 5
  MOD: 4
  TMB: 3
# Right hand only, assume left hand is the same + 0.05
# Use None for reserved keys
key_penalties:
  NUM: []
  TOP: [5, 3, 1.5, 2.0, 7.5]
  HOM: [2, 0, 0.0, 0.5, 2.0]
  BOT: [3.5, 0.5, 2.0, 2.5, 4]
  MOD: [4, 4.5, 5, 5.5]
  TMB: [3, 0, 2]
# Slight penalty to the left hand keys to force more common keys on the right hand
left_hand_penalty: 0.05
fingers:
  NUM: []
  TOP: [I, I, M, R, R]
  HOM: [I, I, M, R, P]
  BOT: [I, I, M, R, P]
  MOD: [I, M, R, P]
  TMB: [T, T, T]
penalties: # Some penalties are WPM drops from https://mathematicalmulticore.wordpress.com/2011/11/27/typing-data-preliminary-analysis/
  location: 10
  layers: [0, 5, 5]
  same_finger: 10
  same_hand: 10
  alternating_hand: 5
  long_jump_finger: 10
  long_jump_consecutive: 5
  long_jump_sandwich: 3
  long_jump_hand: 2
  roll_reversal: 10
  roll_out: 1
  roll_in: -10
  twist: 5
  finger_disbalance: 3
  split_group: 1
  frozen_keys: 1
  blocked_indexes: 1
# This should probably be rather passed in as a layout
frozen_keys:
  "\t": 38
  "e": 39
  "\e": 40
  "\b": 41
  " ": 42
  "\n": 43
  "↓": 32
  "↑": 33
  "←": 34
  "→": 35
  "0": 70
  "2": 60
  "4": 61
  "6": 62
  "8": 63
  "1": 67
  "3": 57
  "5": 56
  "7": 55
  "9": 54
  "+": 58
  "-": 59
  "*": 68
  "/": 69
  "[": 36
  "]": 37
  "=": 14
  ",": 15
  ":": 24
  ".": 25
blocked_indexes: [82, 83, 84, 85, 86, 87]
extra_groups:
  r_brackets: ["(", ")"]
  s_brackets: ["[", "]"]
  c_brackets: ["{", "}"]
  a_brackets: ["<", ">"]
ignore_loc_penality_for_chars: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "+", "-", "*", "/", "#"]
annealing:
  num_layers: 2
  num_layouts: 64
  init_temperature: 10
  num_processes: 16
  num_iters: 10000
  iters_per_cycle: 200 # Don't set it too low or one version will use up all slots
  keep_top: 2 # How many to keep from each pool
  cooling_rate: 10
# Skip most lines to improve efficiency
text_downsampling: 30
disable_eval_tqdm: True
